github action build_release another attempt to fix release process with README.md update

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -15,17 +15,21 @@ jobs:
         VERSION=${GITHUB_REF_NAME#v}
         echo Version: $VERSION
         echo "VERSION=$VERSION" >> $GITHUB_ENV
+
     - name: Checkout sources
       uses: actions/checkout@v4.1.7
       with:
         fetch-depth: 0
+
     - name: Setup Java
       uses: actions/setup-java@v4.2.2
       with:
         distribution: 'temurin'
         java-version: 22
+
     - name: Setup Gradle
       uses: gradle/actions/setup-gradle@v4
+
     - name: Build
       run: ./gradlew -Pversion=${VERSION} build sourcesJar javadocJar publishToSonatype closeAndReleaseSonatypeStagingRepository
       env:
@@ -35,10 +39,23 @@ jobs:
         ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
         ORG_GRADLE_PROJECT_sonatypeUser: ${{ secrets.SONATYPE_USER }}
         ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
-    - name: Switch to branch HEAD
-      run: git checkout $(git branch --contains ${{ github.event.release.tag_name }})
+
+    - name: Find branch from tag
+      id: find-branch
+      run: |
+        BRANCH=$(git branch -r --contains ${{ github.event.release.tag_name }} | grep -v '\->' | sed 's/origin\///' | head -n 1)
+        if [ -z "$BRANCH" ]; then
+          echo "Branch not found for tag $TAG"
+          exit 1
+        fi
+        echo "::set-output name=branch::$BRANCH"        
+
+    - name: Checkout branch HEAD
+      run: git checkout ${{ steps.find-branch.outputs.branch }}
+
     - name: Update README
       run: sed -i 's/com\.xemantic\.kotlin:xemantic-kotlin-swing-dsl-\(core\|test\):[0-9]\+\(\.[0-9]\+\)*\>/com.xemantic.kotlin:xemantic-kotlin-swing-dsl-\1:${VERSION}/g' README.md
+
     - name: Commit README
       uses: stefanzweifel/git-auto-commit-action@v5
       with:
